### ISSUE TITLE
目前qwen不支持张量并行？

### ISSUE THREAD

**Issue by Coder-nlper** [Tlntin/Qwen-7B-Chat-TensorRT-LLM#10]
我测试了下。张量并行会报错，具体信息如下：
[10/25/2023-09:08:16] [TRT] [E] 3: [executionContext.cpp::setInputShape::2257] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2257, condition: engineDims.d[i] == dims.d[i] Static dimension mismatch while setting input shape.)
Traceback (most recent call last):
  File "/api/example/tensorrt_llm/qwen/summarize.py", line 380, in <module>
    main(args)
  File "/api/example/tensorrt_llm/qwen/summarize.py", line 257, in main
    summary, _ = summarize_tensorrt_llm(datapoint)
  File "/api/example/tensorrt_llm/qwen/summarize.py", line 230, in summarize_tensorrt_llm
    output_ids = tensorrt_llm_qwen.decode(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 514, in wrapper
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1887, in decode
    return self.decode_regular(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1659, in decode_regular
    should_stop, next_step_buffer, tasks, context_lengths, host_context_lengths, attention_mask, logits = self.handle_per_step(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1430, in handle_per_step
    self.runtime._set_shape(context, ctx_shape)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 202, in _set_shape
    raise ValueError(
ValueError: Couldn't assign past_key_value_0 with shape torch.Size([1, 2, 8, 374, 128]), engine supports [min, opt, max] = [(1, 2, 16, 0, 128), (1, 2, 16, 768, 128), (2, 2, 16, 1536, 128)]

**Comment by Tlntin** [comment]
额，应该是的。
因为我只有单卡，没做多卡的测试。

**Comment by zhaohb** [comment]
@Coder-nlper 正在测试支持哈

**Comment by zhaohb** [comment]
@Coder-nlper 已经支持tp了，可以更新代码测试下，readme里面有详细说明

**Comment by Coder-nlper** [comment]
> @Coder-nlper 已经支持tp了，可以更新代码测试下，readme里面有详细说明

@zhaohb 感谢大佬
