### ISSUE TITLE
RuntimeError: [TensorRT-LLM][ERROR] Assertion failed: Unsupported Arch (/opt/tritonserver/TensorRT-LLM/cpp/tensorrt_llm/kernels/cutlass_kernels/cutlass_preprocessors.cpp:147)

### ISSUE THREAD

**Issue by tms2003** [Tlntin/Qwen-7B-Chat-TensorRT-LLM#15]
P40下出错：
```
python3 build.py --use_weight_only --weight_only_precision=int8
[10/28/2023-03:06:29] [TRT-LLM] [I] Serially build TensorRT engines.
[10/28/2023-03:06:29] [TRT] [I] [MemUsageChange] Init CUDA: CPU +9, GPU +0, now: CPU 111, GPU 148 (MiB)
[10/28/2023-03:06:30] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +245, GPU +40, now: CPU 491, GPU 188 (MiB)
[10/28/2023-03:06:30] [TRT-LLM] [W] Invalid timing cache, using freshly created one
[10/28/2023-03:06:49] [TRT-LLM] [I] Loading HF QWen ... from /data/llm/Qwen-7B-Chat-TensorRT-LLM/qwen/qwen_7b_chat
[10/28/2023-03:06:49] Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经开始使用Qwen-7B，千万注意不要使用错误代码和模型。
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 15.47it/s]
[10/28/2023-03:06:50] [TRT-LLM] [I] HF QWen loaded. Total time: 00:00:01
[10/28/2023-03:06:50] [TRT-LLM] [I] Loading weights from HF QWen...
Converting...:   1%|▏                           | 2/259 [00:03<06:40,  1.56s/it]
Traceback (most recent call last):
  File "/data/llm/Qwen-7B-Chat-TensorRT-LLM/qwen/build.py", line 645, in <module>
    build(0, args)
  File "/data/llm/Qwen-7B-Chat-TensorRT-LLM/qwen/build.py", line 615, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/data/llm/Qwen-7B-Chat-TensorRT-LLM/qwen/build.py", line 480, in build_rank_engine
    load_from_hf_qwen(
  File "/data/llm/Qwen-7B-Chat-TensorRT-LLM/qwen/weight.py", line 529, in load_from_hf_qwen
    processed_torch_weights, torch_weight_scales = torch.ops.fastertransformer.symmetric_quantize_last_axis_of_batched_matrix(
  File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 692, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: [TensorRT-LLM][ERROR] Assertion failed: Unsupported Arch (/opt/tritonserver/TensorRT-LLM/cpp/tensorrt_llm/kernels/cutlass_kernels/cutlass_preprocessors.cpp:147)
1       0x7fc0c270bb7e tensorrt_llm::common::throwRuntimeError(char const*, int, std::string const&) + 102
2       0x7fc0c279683e tensorrt_llm::kernels::cutlass_kernels::getLayoutDetailsForTransform(tensorrt_llm::kernels::cutlass_kernels::QuantType) + 430
3       0x7fc0c2796959 tensorrt_llm::kernels::cutlass_kernels::preprocess_weights_for_mixed_gemm(signed char*, signed char const*, std::vector<unsigned long, std::allocator<unsigned long> > const&, tensorrt_llm::kernels::cutlass_kernels::QuantType) + 57
4       0x7fc0c279dd3e void tensorrt_llm::kernels::cutlass_kernels::symmetric_quantize<__half, __half>(signed char*, signed char*, __half*, __half const*, std::vector<unsigned long, std::allocator<unsigned long> > const&, tensorrt_llm::kernels::cutlass_kernels::QuantType) + 1502
5       0x7fc0c2745c5d torch_ext::symmetric_quantize_helper(at::Tensor, c10::ScalarType, bool) + 2141
6       0x7fc0c2745e76 torch_ext::symmetric_quantize_last_axis_of_batched_matrix(at::Tensor, c10::ScalarType) + 70
7       0x7fc0c274b28d c10::impl::make_boxed_from_unboxed_functor<c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<std::vector<at::Tensor, std::allocator<at::Tensor> > (*)(at::Tensor, c10::ScalarType), std::vector<at::Tensor, std::allocator<at::Tensor> >, c10::guts::typelist::typelist<at::Tensor, c10::ScalarType> >, true>::call(c10::OperatorKernel*, c10::OperatorHandle const&, c10::DispatchKeySet, std::vector<c10::IValue, std::allocator<c10::IValue> >*) + 141
8       0x7fc1c85b5362 c10::Dispatcher::callBoxed(c10::OperatorHandle const&, std::vector<c10::IValue, std::allocator<c10::IValue> >*) const + 562
9       0x7fc1c834c8c3 torch::jit::invokeOperatorFromPython(std::vector<std::shared_ptr<torch::jit::Operator>, std::allocator<std::shared_ptr<torch::jit::Operator> > > const&, pybind11::args, pybind11::kwargs const&, c10::optional<c10::DispatchKey>) + 1155
10      0x7fc1c834d1b8 torch::jit::_get_operation_for_overload_or_packet(std::vector<std::shared_ptr<torch::jit::Operator>, std::allocator<std::shared_ptr<torch::jit::Operator> > > const&, c10::Symbol, pybind11::args, pybind11::kwargs const&, bool, c10::optional<c10::DispatchKey>) + 1448
11      0x7fc1c82311a0 /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_python.so(+0x8021a0) [0x7fc1c82311a0]
12      0x7fc1c7e1dac4 /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_python.so(+0x3eeac4) [0x7fc1c7e1dac4]
13      0x55d806e73e0e python3(+0x15fe0e) [0x55d806e73e0e]
14      0x55d806e8312b PyObject_Call + 187
15      0x55d806e5f2c1 _PyEval_EvalFrameDefault + 11121
16      0x55d806e69784 _PyObject_FastCallDictTstate + 196
17      0x55d806e7f54c _PyObject_Call_Prepend + 92
18      0x55d806f981e0 python3(+0x2841e0) [0x55d806f981e0]
19      0x55d806e6a5eb _PyObject_MakeTpCall + 603
20      0x55d806e631f1 _PyEval_EvalFrameDefault + 27297
21      0x55d806e7470c _PyFunction_Vectorcall + 124
22      0x55d806e5e0d1 _PyEval_EvalFrameDefault + 6529
23      0x55d806e7470c _PyFunction_Vectorcall + 124
24      0x55d806e5ce0d _PyEval_EvalFrameDefault + 1725
25      0x55d806e7470c _PyFunction_Vectorcall + 124
26      0x55d806e5ce0d _PyEval_EvalFrameDefault + 1725
27      0x55d806f4de56 python3(+0x239e56) [0x55d806f4de56]
28      0x55d806f4dcf6 PyEval_EvalCode + 134
29      0x55d806f787d8 python3(+0x2647d8) [0x55d806f787d8]
30      0x55d806f720bb python3(+0x25e0bb) [0x55d806f720bb]
31      0x55d806f78525 python3(+0x264525) [0x55d806f78525]
32      0x55d806f77a08 _PyRun_SimpleFileObject + 424
33      0x55d806f77653 _PyRun_AnyFileObject + 67
34      0x55d806f6a41e Py_RunMain + 702
35      0x55d806f40cad Py_BytesMain + 45
36      0x7fc21de75d90 /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7fc21de75d90]
37      0x7fc21de75e40 __libc_start_main + 128
38      0x55d806f40ba5 _start + 37
root@941c037c9f0f:/data/llm/Qwen-7B-Chat-TensorRT-LLM/qwen# python3 run.py
Traceback (most recent call last):
  File "/data/llm/Qwen-7B-Chat-TensorRT-LLM/qwen/run.py", line 516, in <module>
    generate(**vars(args))
  File "/data/llm/Qwen-7B-Chat-TensorRT-LLM/qwen/run.py", line 397, in generate
    ) = get_model(tokenizer_dir, engine_dir, log_level)
  File "/data/llm/Qwen-7B-Chat-TensorRT-LLM/qwen/run.py", line 305, in get_model
    with open(config_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/llm/Qwen-7B-Chat-TensorRT-LLM/qwen/trt_engines/fp16/1-gpu/config.json'

```
cuda 12.2 ,driver:535

请问是什么原因，如何解决？

**Comment by Tlntin** [comment]
不支持的架构。
简称不支持你的卡。
目前只支持30/40系列，V100/A100后的卡。
参考该图:
![1698320714700.jpg](https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/assets/28218658/d3dce821-af15-434e-a0cf-26c9cb25bded)

**Comment by tms2003** [comment]
@Tlntin 
请问这个是指TensorRT LLM不支持，还是qwen这个不支持？你的页面来自哪个链接？谢谢！

**Comment by Tlntin** [comment]
> @Tlntin 
> 请问这个是指TensorRT LLM不支持，还是qwen这个不支持？你的页面来自哪个链接？谢谢！

TensorRT-LLM不支持。

页面来自官方直播，我截的图，暂时没有链接。

**Comment by tms2003** [comment]
好的，明白了，谢谢！

**Comment by Tlntin** [comment]
实在没有合适的显卡可以用AutoDL上面选一个，然后按教程编译就行，参考教程：https://zhuanlan.zhihu.com/p/663915644
我编译了一个，正在申请公开共享镜像，如果急用可以把你的AutoDL id发我，然后我设置指定共享镜像给你。
