### ISSUE TITLE
3090上qwen-14b-4bit转换失败

### ISSUE THREAD

**Issue by tms2003** [Tlntin/Qwen-7B-Chat-TensorRT-LLM#23]
修改了配置文件，

命令行为:
python3 build.py --use_weight_only --weight_only_precision=int4

```
[11/06/2023-11:38:58] [TRT-LLM] [I] Serially build TensorRT engines.
[11/06/2023-11:38:58] [TRT] [I] [MemUsageChange] Init CUDA: CPU +13, GPU +0, now: CPU 115, GPU 271 (MiB)
[11/06/2023-11:39:02] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1799, GPU +312, now: CPU 2050, GPU 583 (MiB)
[11/06/2023-11:39:02] [TRT-LLM] [W] Invalid timing cache, using freshly created one
 /app/tensorrt_llm/examples/qwen/c-model/Qwen-14B-Chat-Int4/1-gpu not exists, will get weight from qwen local 
[11/06/2023-11:39:24] [TRT-LLM] [I] Loading HF QWen ... from /app/tensorrt_llm/examples/qwen/Qwen-14B-Chat-Int4
[11/06/2023-11:39:24] Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经开始使用Qwen-7B，千万注意不要使用错误代码和模型。
[11/06/2023-11:39:24] Try importing flash-attention for faster inference...
...
[11/06/2023-12:16:08] [TRT] [W] Tactic Device request: 40125MB Available: 24259MB. Device memory is insufficient to use tactic.
[11/06/2023-12:16:08] [TRT] [W] UNSUPPORTED_STATESkipping tactic 3 due to insufficient memory on requested size of 40125 detected for tactic 0x000000000000001b.
[11/06/2023-12:16:08] [TRT] [W] Tactic Device request: 40125MB Available: 24259MB. Device memory is insufficient to use tactic.
[11/06/2023-12:16:08] [TRT] [W] UNSUPPORTED_STATESkipping tactic 4 due to insufficient memory on requested size of 40125 detected for tactic 0x000000000000001f.
[11/06/2023-12:16:13] [TRT] [I] [GraphReduction] The approximate region cut reduction algorithm is called.
[11/06/2023-12:16:13] [TRT] [I] Detected 48 inputs and 41 output network tensors.
[11/06/2023-12:16:13] [TRT] [E] 4: Internal error: plugin node QWenForCausalLM/layers/0/attention/PLUGIN_V2_GPTAttention_1 requires 31664978560 bytes of scratch space, but only 25438126080 is available. Try increasing the workspace size with IBuilderConfig::setMemoryPoolLimit().

[11/06/2023-12:16:13] [TRT] [E] 4: [pluginV2Builder.cpp::makeRunner::519] Error Code 4: Internal Error (Internal error: plugin node QWenForCausalLM/layers/0/attention/PLUGIN_V2_GPTAttention_1 requires 31664978560 bytes of scratch space, but only 25438126080 is available. Try increasing the workspace size with IBuilderConfig::setMemoryPoolLimit().
)
[11/06/2023-12:16:13] [TRT-LLM] [E] Engine building failed, please check the error log.
[11/06/2023-12:16:13] [TRT-LLM] [I] Config saved to /app/tensorrt_llm/examples/qwen/trt_engines/int4/1-gpu/config.json.
Traceback (most recent call last):
  File "/app/tensorrt_llm/examples/qwen/build.py", line 725, in <module>
    build(0, args)
  File "/app/tensorrt_llm/examples/qwen/build.py", line 697, in build
    assert engine is not None, f'Failed to build engine for rank {cur_rank}'
AssertionError: Failed to build engine for rank 0

```

很明显的显存不足。但按理其实是可能的，因为3090有24G显存，14B-4bit应当在10G以内。但应当是转换过程的问题，能解决否？

**Comment by Tlntin** [comment]
Cpu内存多少呢？有没有64G?
可用磁盘有多少呢？

**Comment by Tlntin** [comment]
个人建议可以试试加swap，感觉是CPU内存不够，qwen-14b int8 weight only我在3090, CPU 64G内存上测试过，没有问题。

**Comment by tms2003** [comment]
找到原因了。因为我是通过14b-4bit转的，直接通过14b转就没有问题。谢谢！

**Comment by Tlntin** [comment]
不客气
