### ISSUE TITLE
运行qwen/run.py报错，libnvinfer_plugin_tensorrt_llm.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by taojingcong** [Tlntin/Qwen-7B-Chat-TensorRT-LLM#3]
Traceback (most recent call last):
  File "/workspace/Qwen-7B-Chat-TensorRT-LLM-main/Qwen-7B-Chat-TensorRT-LLM-main/tensorrt_llm_july-release-v1/examples/qwen/run.py", line 17, in <module>
    import tensorrt_llm
  File "/workspace/Qwen-7B-Chat-TensorRT-LLM-main/Qwen-7B-Chat-TensorRT-LLM-main/tensorrt_llm_july-release-v1/tensorrt_llm/__init__.py", line 43, in <module>
    _common._init(log_level="error")
  File "/workspace/Qwen-7B-Chat-TensorRT-LLM-main/Qwen-7B-Chat-TensorRT-LLM-main/tensorrt_llm_july-release-v1/tensorrt_llm/_common.py", line 25, in _init
    _load_plugin_lib()
  File "/workspace/Qwen-7B-Chat-TensorRT-LLM-main/Qwen-7B-Chat-TensorRT-LLM-main/tensorrt_llm_july-release-v1/tensorrt_llm/plugin/plugin.py", line 15, in _load_plugin_lib
    handle = ctypes.CDLL(plugin_lib, mode=ctypes.RTLD_GLOBAL)
  File "/opt/conda/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /workspace/Qwen-7B-Chat-TensorRT-LLM-main/Qwen-7B-Chat-TensorRT-LLM-main/tensorrt_llm_july-release-v1/tensorrt_llm/libs/libnvinfer_plugin_tensorrt_llm.so: cannot open shared object file: No such file or directory

是环境哪里没有装好吗

**Comment by D1-3105** [comment]
What's the problem solution with run.py?
