### ISSUE TITLE
使用Langchain-Chatchat出现的问题：Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it

### ISSUE THREAD

**Issue by tms2003** [Tlntin/Qwen-7B-Chat-TensorRT-LLM#34]
已经按 https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/blob/release/0.5.0/docs/trt_llm_deploy_langchain.md进行了相应的处理。

包括:

3）修改模型配置文件configs/model_config.py，修改LLM_MODEL为OpenAI

"api_base_url": "https://api.openai.com/v1",
        "api_key": "your OPENAI_API_KEY",

改为localhost:8000/v1，测试可以访问。

在web界面上:
<img width="438" alt="image" src="https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/assets/18380506/6690c64b-0943-4208-9785-692e78a40d6b">

发现它会重复两次。随便选一个openai。对话出错：
<img width="854" alt="image" src="https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/assets/18380506/9b50aa5a-5c43-424f-8032-9a5af5621bc2">
控制台显示为：
```
 Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` a>
2023-11-18 10:11:31,927 - utils.py[line:188] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sendi>
{'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://12>
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'htt>


```
> 由于我的20000端口被占用，所以将server_config.py的20000改为了23000

在localhost:7861/docs#/Chat/openai_chat_chat_fastchat_post
上进行单独的测试，结果为：

<img width="1172" alt="image" src="https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/assets/18380506/fdca3cc7-e219-4620-9b97-85f0a2041b5d">

无返回，但 控制台上显示：
```
INFO:     127.0.0.1:58432 - "POST /chat/chat HTTP/1.1" 200 OK
2023-11-18 10:23:01,528 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/incar/miniconda3/envs/llm/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_>
    result = await app(  # type: ignore[func-returns-value]
  File "/home/incar/miniconda3/envs/llm/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/incar/miniconda3/envs/llm/lib/python3.9/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/incar/miniconda3/envs/llm/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/incar/miniconda3/envs/llm/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/incar/miniconda3/envs/llm/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/incar/miniconda3/envs/llm/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/incar/miniconda3/envs/llm/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)

pydantic.error_wrappers.ValidationError: 1 validation error for ChatOpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` >
2023-11-18 10:23:01,529 - utils.py[line:188] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sendi>
INFO:     10.147.20.80:50467 - "GET /swagger-ui-bundle.js.map HTTP/1.1" 404 Not Found
INFO:     10.147.20.80:50468 - "GET /swagger-ui.css.map HTTP/1.1" 404 Not Found
openai.api_key='EMPTY'
openai.api_base='http://127.0.0.1:23000/v1'
model='OpenAI' messages=[OpenAiMessage(role='user', content='hello')] temperature=0.7 n=1 max_tokens=0 stop=[] stream=False pres>


```
看上去，它向http://127.0.0.1:23000/v1发送请求，然后出错了。我认为是否是应当改为8000端口，但改后程序无法启动，说端口被占用。那么，就似乎是通过http://127.0.0.1:23000/v1转向http://127.0.0.1:8000/v1的问题。请问是这个问题吗？如何解决？

**Comment by Tlntin** [comment]
`Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it` 可以试试填一下这个OPENAI_API_KEY，里面任意填一下。

**Comment by tms2003** [comment]
@Tlntin 谢谢你的指教。现在的结果变成了：


2023-11-18 11:23:24,844 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
2023-11-18 11:23:24,894 - before_sleep.py[line:65] - WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<loca>
2023-11-18 11:23:28,902 - utils.py[line:26] - ERROR: APIConnectionError: Caught exception: Error communicating with OpenAI


看来仍然是重定向没有起作用。

**Comment by Tlntin** [comment]
可以看看你的langchain openai模块版本。
如果你是langchain-chat 0.2.6, 请使用openai 0.2.8或者0.4.0

**Comment by Tlntin** [comment]
其他情况可以参考这位的https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/issues/32

**Comment by tms2003** [comment]
使用了多个不同版本的openapi,有0.2.8、0.4.0、0.8、0.18和1.3.2、1.3.3都不行。
现阶段发现它发起了请求到api.py的8000端口的api上，会在控制台上打印出下列信息：
```
INFO:     127.0.0.1:59098 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:38662 - "POST /v1/chat/completions HTTP/1.1" 200 OK
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
```

在chain_lain端的出错信息则为：
```
2023-11-19 11:37:32,657 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:44582 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-11-19 11:37:32,665 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None}}
2023-11-19 11:37:32,682 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:44582 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-19 11:37:32,686 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
received input message:
{'history': [],
 'max_tokens': None,
 'model_name': 'OpenAI',
 'prompt_name': 'default',
 'query': 'helllo',
 'stream': True,
 'temperature': 0.7}
INFO:     127.0.0.1:44582 - "POST /chat/chat HTTP/1.1" 200 OK
2023-11-19 11:37:37,310 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
2023-11-19 11:37:37,341 - before_sleep.py[line:65] - WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
2023-11-19 11:37:41,348 - utils.py[line:26] - ERROR: APIConnectionError: Caught exception: Error communicating with OpenAI

```

**Comment by Tlntin** [comment]
好的，我待会本机测试一下你的情况。

**Comment by Tlntin** [comment]
我本地测试的openai版本是0.28.1
在不改端口的情况下，没有任何问题。

**Comment by Tlntin** [comment]
改了端口为23000后，也正常启动，对话仍然正常
![image](https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/assets/28218658/56678cb5-8cd0-432c-b109-3f32865cf51d)

**Comment by Tlntin** [comment]
建议你，进入api调试页面测试测试。大概率是openai版本或者是网络问题（比如ip地址填错了？没有映射？你可以用postman请求一下试试）
开启langchain-chatchat后，可以打开下面这个链接进入在线调试页面，相当于postman。
http://127.0.0.1:7861/docs#/Chat/chat_chat_chat_post

![image](https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/assets/28218658/5f404c20-e036-4aad-89c2-bd360a97df5f)

![image](https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/assets/28218658/e72bbc82-9a2c-4ab6-abc0-05e55c9356ca)

**Comment by tms2003** [comment]
终于找到原因了，我把原来的https:中的s没有删除，所以引起一堆错误！
